n1=int(input("Enter number 1:"))
n2=int(input("Enter number 2:"))
print("***Aritmetic Operations***")
print("Addition =",n1+n2)
print("Subtraction =",n1-n2)
print("Multiplcation =",n1*n2)
print("Division =",n1/n2)
print("Floor Division =",n1//n2)
print("Exponential =",n1**n2)
print("Modulus =",n1%n2)
